# Generated by Django 3.2 on 2025-12-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('attendence_time', models.DateTimeField(auto_now_add=True)),
                ('attendence_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=3)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('liveness_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('confirmPassword', models.CharField(max_length=500)),
                ('fingerprint_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='image_md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
